[book]
authors = ["Andrei Borisenko"]
language = "en"
src = "src"
title = "GoGreement - Go Linter for Enforcing Code Agreements"

[output.html]
git-repository-url = "https://github.com/a14e/gogreement"
git-repository-icon = "fa-github"
