name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install tooling via Makefile
        run: make install

      - name: Run project CI
        # Pass TEST_ARGS to properly calculate coverage excluding testdata directories.
        # tr and sed convert go list output from newline-separated to comma-separated format required by -coverpkg
        run: make ci TEST_ARGS="-covermode=atomic -coverpkg=$(go list ./... | grep -v testdata | tr '\n' ',' | sed 's/,$//') -coverprofile=coverage.txt"

      - name: Run gogreement on itself (dogfooding)
        run: ./gogreement ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}